name: Playwright Tests

on:
  push:
    branches:
      - main  # Ou o branch que você deseja monitorar

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Você pode ajustar a versão do Node.js, se necessário

      # Instalar dependências
      - name: Install dependencies
        run: |
          npm install
          npx playwright install-deps

      # Rodar os testes do Playwright
      - name: Run Playwright Tests
        run: |
          npx playwright test
